
// This file has been generated by the GUI designer. Do not modify.

public partial class LoginWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Image MainLogo;

	private global::Gtk.Label TitleLabel;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Image UserLogo;

	private global::Gtk.Label UsernameLabel;

	private global::Gtk.Entry UserEntry;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Image PwdLogo;

	private global::Gtk.Label UserpwdLabel;

	private global::Gtk.Entry PwdEntry;

	private global::Gtk.HBox hbox4;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Button CancelBtn;

	private global::Gtk.Button LoginBtn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget LoginWindow
		this.WidthRequest = 450;
		this.HeightRequest = 300;
		this.Name = "LoginWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Welcome");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		// Container child LoginWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.MainLogo = new global::Gtk.Image();
		this.MainLogo.Name = "MainLogo";
		this.MainLogo.Xpad = 50;
		this.MainLogo.Ypad = 25;
		this.hbox5.Add(this.MainLogo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.MainLogo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.TitleLabel = new global::Gtk.Label();
		this.TitleLabel.Name = "TitleLabel";
		this.TitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Title");
		this.TitleLabel.Justify = ((global::Gtk.Justification)(2));
		this.hbox5.Add(this.TitleLabel);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.TitleLabel]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UserLogo = new global::Gtk.Image();
		this.UserLogo.Name = "UserLogo";
		this.UserLogo.Xpad = 20;
		this.UserLogo.Ypad = 10;
		this.hbox2.Add(this.UserLogo);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.UserLogo]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UsernameLabel = new global::Gtk.Label();
		this.UsernameLabel.Name = "UsernameLabel";
		this.UsernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("User             :");
		this.UsernameLabel.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add(this.UsernameLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.UsernameLabel]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UserEntry = new global::Gtk.Entry();
		this.UserEntry.WidthRequest = 241;
		this.UserEntry.HeightRequest = 30;
		this.UserEntry.CanFocus = true;
		this.UserEntry.Name = "UserEntry";
		this.UserEntry.IsEditable = true;
		this.UserEntry.InvisibleChar = '•';
		this.hbox2.Add(this.UserEntry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.UserEntry]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Padding = ((uint)(10));
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.PwdLogo = new global::Gtk.Image();
		this.PwdLogo.Name = "PwdLogo";
		this.PwdLogo.Xpad = 20;
		this.PwdLogo.Ypad = 10;
		this.hbox3.Add(this.PwdLogo);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.PwdLogo]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UserpwdLabel = new global::Gtk.Label();
		this.UserpwdLabel.Name = "UserpwdLabel";
		this.UserpwdLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Password :");
		this.hbox3.Add(this.UserpwdLabel);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.UserpwdLabel]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.PwdEntry = new global::Gtk.Entry();
		this.PwdEntry.WidthRequest = 241;
		this.PwdEntry.HeightRequest = 30;
		this.PwdEntry.CanFocus = true;
		this.PwdEntry.Name = "PwdEntry";
		this.PwdEntry.IsEditable = true;
		this.PwdEntry.Visibility = false;
		this.PwdEntry.InvisibleChar = '•';
		this.hbox3.Add(this.PwdEntry);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.PwdEntry]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Padding = ((uint)(10));
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.BorderWidth = ((uint)(7));
		// Container child hbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.hbox4.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hseparator1]));
		w12.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.CancelBtn = new global::Gtk.Button();
		this.CancelBtn.WidthRequest = 100;
		this.CancelBtn.CanFocus = true;
		this.CancelBtn.Name = "CancelBtn";
		this.CancelBtn.UseUnderline = true;
		this.CancelBtn.BorderWidth = ((uint)(5));
		this.CancelBtn.Label = global::Mono.Unix.Catalog.GetString("Cancel");
		this.hbox4.Add(this.CancelBtn);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.CancelBtn]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		w13.Padding = ((uint)(10));
		// Container child hbox4.Gtk.Box+BoxChild
		this.LoginBtn = new global::Gtk.Button();
		this.LoginBtn.WidthRequest = 100;
		this.LoginBtn.CanFocus = true;
		this.LoginBtn.Name = "LoginBtn";
		this.LoginBtn.UseUnderline = true;
		this.LoginBtn.BorderWidth = ((uint)(5));
		this.LoginBtn.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.hbox4.Add(this.LoginBtn);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.LoginBtn]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 450;
		this.DefaultHeight = 326;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.CancelBtn.Clicked += new global::System.EventHandler(this.On_CancelBtn_Clicked);
		this.LoginBtn.Clicked += new global::System.EventHandler(this.On_LoginBtn_Clicked);
	}
}
