
// This file has been generated by the GUI designer. Do not modify.
namespace ScoreManagement.GtkSharp
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FunctionsAction;

		private global::Gtk.Action ChangePwdAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.ComboBox ConditionCombox;

		private global::Gtk.Entry ConditionEntry;

		private global::Gtk.Button ScoreQueryBtn;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView ScoreTreeView;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label5;

		private global::Gtk.Entry NameEntry;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBox CreditCombox;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label6;

		private global::Gtk.Entry IdEntry;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button QueryCourseBtn;

		private global::Gtk.Button AddCourseBtn;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button ModifyBtn;

		private global::Gtk.Button DeleteCourseBtn;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView CourseTreeView;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScoreManagement.GtkSharp.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FunctionsAction = new global::Gtk.Action("FunctionsAction", global::Mono.Unix.Catalog.GetString("_Functions"), null, null);
			this.FunctionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Functions");
			w1.Add(this.FunctionsAction, null);
			this.ChangePwdAction = new global::Gtk.Action("ChangePwdAction", global::Mono.Unix.Catalog.GetString("ChangePwd"), null, null);
			this.ChangePwdAction.ShortLabel = global::Mono.Unix.Catalog.GetString("ChangePwd");
			w1.Add(this.ChangePwdAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.WidthRequest = 800;
			this.HeightRequest = 400;
			this.Name = "ScoreManagement.GtkSharp.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child ScoreManagement.GtkSharp.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'FunctionsAction\' action=\'FunctionsAction" +
					"\'><menuitem name=\'ChangePwdAction\' action=\'ChangePwdAction\'/></menu></menubar></" +
					"ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.BorderWidth = ((uint)(2));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 8;
			this.hbox1.BorderWidth = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Please set query condition :");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ConditionCombox = global::Gtk.ComboBox.NewText();
			this.ConditionCombox.AppendText(global::Mono.Unix.Catalog.GetString("Name"));
			this.ConditionCombox.AppendText(global::Mono.Unix.Catalog.GetString("Id"));
			this.ConditionCombox.WidthRequest = 143;
			this.ConditionCombox.Name = "ConditionCombox";
			this.ConditionCombox.Active = 0;
			this.hbox1.Add(this.ConditionCombox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ConditionCombox]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ConditionEntry = new global::Gtk.Entry();
			this.ConditionEntry.CanFocus = true;
			this.ConditionEntry.Name = "ConditionEntry";
			this.ConditionEntry.IsEditable = true;
			this.ConditionEntry.InvisibleChar = '•';
			this.hbox1.Add(this.ConditionEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ConditionEntry]));
			w5.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ScoreQueryBtn = new global::Gtk.Button();
			this.ScoreQueryBtn.WidthRequest = 90;
			this.ScoreQueryBtn.CanFocus = true;
			this.ScoreQueryBtn.Name = "ScoreQueryBtn";
			this.ScoreQueryBtn.UseUnderline = true;
			this.ScoreQueryBtn.Label = global::Mono.Unix.Catalog.GetString("Query");
			this.hbox1.Add(this.ScoreQueryBtn);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ScoreQueryBtn]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(4));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ScoreTreeView = new global::Gtk.TreeView();
			this.ScoreTreeView.CanFocus = true;
			this.ScoreTreeView.Name = "ScoreTreeView";
			this.GtkScrolledWindow.Add(this.ScoreTreeView);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w9.Position = 1;
			this.notebook1.Add(this.vbox2);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Score Query");
			this.notebook1.SetTabLabel(this.vbox2, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(3));
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.WidthRequest = 280;
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 15;
			this.vbox3.BorderWidth = ((uint)(3));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Name   :");
			this.hbox3.Add(this.label5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label5]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.NameEntry = new global::Gtk.Entry();
			this.NameEntry.CanFocus = true;
			this.NameEntry.Name = "NameEntry";
			this.NameEntry.IsEditable = true;
			this.NameEntry.InvisibleChar = '•';
			this.hbox3.Add(this.NameEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.NameEntry]));
			w12.Position = 1;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Credit  :");
			this.hbox5.Add(this.label7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label7]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.CreditCombox = global::Gtk.ComboBox.NewText();
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("6"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("7"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("8"));
			this.CreditCombox.AppendText(global::Mono.Unix.Catalog.GetString("9"));
			this.CreditCombox.Name = "CreditCombox";
			this.hbox5.Add(this.CreditCombox);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.CreditCombox]));
			w15.Position = 1;
			this.vbox3.Add(this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Id            :");
			this.hbox4.Add(this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.IdEntry = new global::Gtk.Entry();
			this.IdEntry.CanFocus = true;
			this.IdEntry.Name = "IdEntry";
			this.IdEntry.IsEditable = true;
			this.IdEntry.InvisibleChar = '•';
			this.hbox4.Add(this.IdEntry);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.IdEntry]));
			w18.Position = 1;
			this.vbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.QueryCourseBtn = new global::Gtk.Button();
			this.QueryCourseBtn.WidthRequest = 80;
			this.QueryCourseBtn.CanFocus = true;
			this.QueryCourseBtn.Name = "QueryCourseBtn";
			this.QueryCourseBtn.UseUnderline = true;
			this.QueryCourseBtn.Label = global::Mono.Unix.Catalog.GetString("Query");
			this.hbox6.Add(this.QueryCourseBtn);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.QueryCourseBtn]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.AddCourseBtn = new global::Gtk.Button();
			this.AddCourseBtn.WidthRequest = 80;
			this.AddCourseBtn.CanFocus = true;
			this.AddCourseBtn.Name = "AddCourseBtn";
			this.AddCourseBtn.UseUnderline = true;
			this.AddCourseBtn.Label = global::Mono.Unix.Catalog.GetString("Add");
			this.hbox6.Add(this.AddCourseBtn);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.AddCourseBtn]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox3.Add(this.hbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Homogeneous = true;
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ModifyBtn = new global::Gtk.Button();
			this.ModifyBtn.WidthRequest = 80;
			this.ModifyBtn.CanFocus = true;
			this.ModifyBtn.Name = "ModifyBtn";
			this.ModifyBtn.UseUnderline = true;
			this.ModifyBtn.Label = global::Mono.Unix.Catalog.GetString("Modify");
			this.hbox7.Add(this.ModifyBtn);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.ModifyBtn]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.DeleteCourseBtn = new global::Gtk.Button();
			this.DeleteCourseBtn.WidthRequest = 80;
			this.DeleteCourseBtn.CanFocus = true;
			this.DeleteCourseBtn.Name = "DeleteCourseBtn";
			this.DeleteCourseBtn.UseUnderline = true;
			this.DeleteCourseBtn.Label = global::Mono.Unix.Catalog.GetString("Delete");
			this.hbox7.Add(this.DeleteCourseBtn);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.DeleteCourseBtn]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox3.Add(this.hbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
			w26.Position = 0;
			w26.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow1.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.CourseTreeView = new global::Gtk.TreeView();
			this.CourseTreeView.CanFocus = true;
			this.CourseTreeView.Name = "CourseTreeView";
			this.GtkScrolledWindow1.Add(this.CourseTreeView);
			this.hbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow1]));
			w28.Position = 1;
			this.notebook1.Add(this.hbox2);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox2]));
			w29.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Course Info Management");
			this.notebook1.SetTabLabel(this.hbox2, this.label3);
			this.label3.ShowAll();
			this.vbox1.Add(this.notebook1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
			w30.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 400;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.ChangePwdAction.Activated += new global::System.EventHandler(this.On_ChangePwd_Activated);
			this.ScoreQueryBtn.Clicked += new global::System.EventHandler(this.On_ScoreQueryBtn_Clicked);
			this.QueryCourseBtn.Clicked += new global::System.EventHandler(this.On_QueryCourseBtn_Clicked);
			this.AddCourseBtn.Clicked += new global::System.EventHandler(this.On_AddCourseBtn_Clicked);
			this.ModifyBtn.Clicked += new global::System.EventHandler(this.On_ModifyCourseBtn_Clicked);
			this.DeleteCourseBtn.Clicked += new global::System.EventHandler(this.On_DeleteCourseBtn_Clicked);
		}
	}
}
