
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action ToolAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action printAction;

	private global::Gtk.Action printPreviewAction;

	private global::Gtk.Action closeAction;

	private global::Gtk.Action undoAction;

	private global::Gtk.Action redoAction;

	private global::Gtk.Action cutAction;

	private global::Gtk.Action copyAction;

	private global::Gtk.Action pasteAction;

	private global::Gtk.Action selectAllAction;

	private global::Gtk.Action colorPickerAction;

	private global::Gtk.Action preferencesAction;

	private global::Gtk.Action ContentsAction;

	private global::Gtk.Action IndexAction;

	private global::Gtk.Action SearchAction;

	private global::Gtk.Action dialogInfoAction;

	private global::Gtk.Action selectFontAction;

	private global::Gtk.Action selectColorAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar Menu;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView TextView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_File");
		w1.Add(this.FileAction, "<Alt><Mod2>f");
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.ToolAction = new global::Gtk.Action("ToolAction", global::Mono.Unix.Catalog.GetString("Tool"), null, null);
		this.ToolAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tool");
		w1.Add(this.ToolAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.openAction = new global::Gtk.Action("openAction", global::Mono.Unix.Catalog.GetString("_Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Open");
		w1.Add(this.openAction, null);
		this.newAction = new global::Gtk.Action("newAction", global::Mono.Unix.Catalog.GetString("_New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_New");
		w1.Add(this.newAction, null);
		this.saveAction = new global::Gtk.Action("saveAction", global::Mono.Unix.Catalog.GetString("_Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Save");
		w1.Add(this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action("saveAsAction", global::Mono.Unix.Catalog.GetString("Save _As"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save _As");
		w1.Add(this.saveAsAction, null);
		this.printAction = new global::Gtk.Action("printAction", global::Mono.Unix.Catalog.GetString("_Print"), null, "gtk-print");
		this.printAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Print");
		w1.Add(this.printAction, null);
		this.printPreviewAction = new global::Gtk.Action("printPreviewAction", global::Mono.Unix.Catalog.GetString("Print Pre_view"), null, "gtk-print-preview");
		this.printPreviewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Print Pre_view");
		w1.Add(this.printPreviewAction, null);
		this.closeAction = new global::Gtk.Action("closeAction", global::Mono.Unix.Catalog.GetString("_Close"), null, "gtk-close");
		this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Close");
		w1.Add(this.closeAction, null);
		this.undoAction = new global::Gtk.Action("undoAction", global::Mono.Unix.Catalog.GetString("_Undo"), null, "gtk-undo");
		this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Undo");
		w1.Add(this.undoAction, null);
		this.redoAction = new global::Gtk.Action("redoAction", global::Mono.Unix.Catalog.GetString("_Redo"), null, "gtk-redo");
		this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Redo");
		w1.Add(this.redoAction, null);
		this.cutAction = new global::Gtk.Action("cutAction", global::Mono.Unix.Catalog.GetString("Cut"), null, "gtk-cut");
		this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cut");
		w1.Add(this.cutAction, null);
		this.copyAction = new global::Gtk.Action("copyAction", global::Mono.Unix.Catalog.GetString("_Copy"), null, "gtk-copy");
		this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Copy");
		w1.Add(this.copyAction, null);
		this.pasteAction = new global::Gtk.Action("pasteAction", global::Mono.Unix.Catalog.GetString("_Paste"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Paste");
		w1.Add(this.pasteAction, null);
		this.selectAllAction = new global::Gtk.Action("selectAllAction", global::Mono.Unix.Catalog.GetString("Select _All"), null, "gtk-select-all");
		this.selectAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Select _All");
		w1.Add(this.selectAllAction, null);
		this.colorPickerAction = new global::Gtk.Action("colorPickerAction", global::Mono.Unix.Catalog.GetString("Customise"), null, "gtk-color-picker");
		this.colorPickerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Customise");
		w1.Add(this.colorPickerAction, null);
		this.preferencesAction = new global::Gtk.Action("preferencesAction", global::Mono.Unix.Catalog.GetString("Options"), null, "gtk-preferences");
		this.preferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Options");
		w1.Add(this.preferencesAction, null);
		this.ContentsAction = new global::Gtk.Action("ContentsAction", global::Mono.Unix.Catalog.GetString("Contents"), null, null);
		this.ContentsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Properties");
		w1.Add(this.ContentsAction, null);
		this.IndexAction = new global::Gtk.Action("IndexAction", global::Mono.Unix.Catalog.GetString("Index"), null, null);
		this.IndexAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Index");
		w1.Add(this.IndexAction, null);
		this.SearchAction = new global::Gtk.Action("SearchAction", global::Mono.Unix.Catalog.GetString("Search"), null, null);
		this.SearchAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Search");
		w1.Add(this.SearchAction, null);
		this.dialogInfoAction = new global::Gtk.Action("dialogInfoAction", global::Mono.Unix.Catalog.GetString("About"), null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.dialogInfoAction, null);
		this.selectFontAction = new global::Gtk.Action("selectFontAction", global::Mono.Unix.Catalog.GetString("_Font"), null, "gtk-select-font");
		this.selectFontAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Font");
		w1.Add(this.selectFontAction, null);
		this.selectColorAction = new global::Gtk.Action("selectColorAction", global::Mono.Unix.Catalog.GetString("_Color"), null, "gtk-select-color");
		this.selectColorAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Color");
		w1.Add(this.selectColorAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Simple Editor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='Menu'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><separator/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='printAction' action='printAction'/><menuitem name='printPreviewAction' action='printPreviewAction'/><separator/><menuitem name='closeAction' action='closeAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='undoAction' action='undoAction'/><menuitem name='redoAction' action='redoAction'/><separator/><menuitem name='cutAction' action='cutAction'/><menuitem name='copyAction' action='copyAction'/><menuitem name='pasteAction' action='pasteAction'/><separator/><menuitem name='selectAllAction' action='selectAllAction'/></menu><menu name='ToolAction' action='ToolAction'><menuitem name='colorPickerAction' action='colorPickerAction'/><menuitem name='preferencesAction' action='preferencesAction'/><menuitem name='selectFontAction' action='selectFontAction'/><menuitem name='selectColorAction' action='selectColorAction'/></menu><menu name='HelpAction' action='HelpAction'><separator/><menuitem name='dialogInfoAction' action='dialogInfoAction'/></menu></menubar></ui>");
		this.Menu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/Menu")));
		this.Menu.Name = "Menu";
		this.vbox1.Add(this.Menu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Menu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TextView = new global::Gtk.TextView();
		this.TextView.CanFocus = true;
		this.TextView.Name = "TextView";
		this.TextView.PixelsAboveLines = 2;
		this.TextView.PixelsBelowLines = 2;
		this.TextView.PixelsInsideWrap = 2;
		this.TextView.LeftMargin = 2;
		this.TextView.RightMargin = 2;
		this.TextView.Indent = 4;
		this.GtkScrolledWindow.Add(this.TextView);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w4.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 566;
		this.DefaultHeight = 416;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler(this.On_OpenAction_Activated);
		this.newAction.Activated += new global::System.EventHandler(this.On_NewAction_Activated);
		this.saveAction.Activated += new global::System.EventHandler(this.On_SaveAction_Activated);
		this.saveAsAction.Activated += new global::System.EventHandler(this.On_SaveAsAction_Activated);
		this.printAction.Activated += new global::System.EventHandler(this.On_PrintAction_Activated);
		this.printPreviewAction.Activated += new global::System.EventHandler(this.On_PrintpreAction_Activated);
		this.closeAction.Activated += new global::System.EventHandler(this.ON_CloseAction_Activated);
		this.dialogInfoAction.Activated += new global::System.EventHandler(this.On_AboutAction_Activated);
		this.selectFontAction.Activated += new global::System.EventHandler(this.On_FontAction_Activated);
		this.selectColorAction.Activated += new global::System.EventHandler(this.On_ColorAction_Activated);
	}
}
