
// This file has been generated by the GUI designer. Do not modify.
namespace BookManagement.Gtksharp
{
	public partial class BookInfoDialog
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label4;

		private global::Gtk.Entry IdEntry;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label5;

		private global::Gtk.Entry TitleEntry;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label6;

		private global::Gtk.Entry AuthorEntry;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label7;

		private global::Gtk.Entry PressEntry;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label8;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Entry IEntryOne;

		private global::Gtk.Label label10;

		private global::Gtk.Entry IEntryTwo;

		private global::Gtk.Label label11;

		private global::Gtk.Entry IEntryThree;

		private global::Gtk.Label label12;

		private global::Gtk.Entry IEntryFour;

		private global::Gtk.Label label13;

		private global::Gtk.Entry IEntryFive;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label9;

		private global::Gtk.Entry PriceEntry;

		private global::Gtk.Button CancelBtn;

		private global::Gtk.Button OkBtn;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget BookManagement.Gtksharp.BookInfoDialog
			this.Name = "BookManagement.Gtksharp.BookInfoDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Add Book");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(12));
			this.AllowGrow = false;
			this.DefaultWidth = 400;
			this.DefaultHeight = 400;
			// Internal child BookManagement.Gtksharp.BookInfoDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 13;
			this.hbox3.BorderWidth = ((uint)(6));
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Id             :");
			this.hbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.IdEntry = new global::Gtk.Entry();
			this.IdEntry.HeightRequest = 30;
			this.IdEntry.Sensitive = false;
			this.IdEntry.Name = "IdEntry";
			this.IdEntry.IsEditable = false;
			this.IdEntry.WidthChars = 0;
			this.IdEntry.InvisibleChar = '•';
			this.hbox3.Add(this.IdEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.IdEntry]));
			w3.Position = 1;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 15;
			this.hbox4.BorderWidth = ((uint)(6));
			// Container child hbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Title       :");
			this.hbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.TitleEntry = new global::Gtk.Entry();
			this.TitleEntry.HeightRequest = 30;
			this.TitleEntry.CanFocus = true;
			this.TitleEntry.Name = "TitleEntry";
			this.TitleEntry.IsEditable = true;
			this.TitleEntry.InvisibleChar = '•';
			this.hbox4.Add(this.TitleEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.TitleEntry]));
			w6.Position = 1;
			this.vbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 12;
			this.hbox5.BorderWidth = ((uint)(6));
			// Container child hbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Author  :");
			this.hbox5.Add(this.label6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.AuthorEntry = new global::Gtk.Entry();
			this.AuthorEntry.HeightRequest = 30;
			this.AuthorEntry.CanFocus = true;
			this.AuthorEntry.Name = "AuthorEntry";
			this.AuthorEntry.IsEditable = true;
			this.AuthorEntry.InvisibleChar = '•';
			this.hbox5.Add(this.AuthorEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.AuthorEntry]));
			w9.Position = 1;
			this.vbox3.Add(this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 12;
			this.hbox6.BorderWidth = ((uint)(6));
			// Container child hbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Press     :");
			this.hbox6.Add(this.label7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label7]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.PressEntry = new global::Gtk.Entry();
			this.PressEntry.HeightRequest = 30;
			this.PressEntry.CanFocus = true;
			this.PressEntry.Name = "PressEntry";
			this.PressEntry.IsEditable = true;
			this.PressEntry.InvisibleChar = '•';
			this.hbox6.Add(this.PressEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.PressEntry]));
			w12.Position = 1;
			this.vbox3.Add(this.hbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 9;
			this.hbox7.BorderWidth = ((uint)(6));
			// Container child hbox7.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("ISBN       :");
			this.hbox7.Add(this.label8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label8]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.IEntryOne = new global::Gtk.Entry();
			this.IEntryOne.WidthRequest = 45;
			this.IEntryOne.HeightRequest = 30;
			this.IEntryOne.CanFocus = true;
			this.IEntryOne.Name = "IEntryOne";
			this.IEntryOne.IsEditable = true;
			this.IEntryOne.MaxLength = 3;
			this.IEntryOne.InvisibleChar = '•';
			this.hbox9.Add(this.IEntryOne);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.IEntryOne]));
			w15.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.hbox9.Add(this.label10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label10]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.IEntryTwo = new global::Gtk.Entry();
			this.IEntryTwo.WidthRequest = 30;
			this.IEntryTwo.HeightRequest = 30;
			this.IEntryTwo.CanFocus = true;
			this.IEntryTwo.Name = "IEntryTwo";
			this.IEntryTwo.IsEditable = true;
			this.IEntryTwo.MaxLength = 1;
			this.IEntryTwo.InvisibleChar = '•';
			this.hbox9.Add(this.IEntryTwo);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.IEntryTwo]));
			w17.Position = 2;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.hbox9.Add(this.label11);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label11]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.IEntryThree = new global::Gtk.Entry();
			this.IEntryThree.WidthRequest = 45;
			this.IEntryThree.HeightRequest = 30;
			this.IEntryThree.CanFocus = true;
			this.IEntryThree.Name = "IEntryThree";
			this.IEntryThree.IsEditable = true;
			this.IEntryThree.MaxLength = 3;
			this.IEntryThree.InvisibleChar = '•';
			this.hbox9.Add(this.IEntryThree);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.IEntryThree]));
			w19.Position = 4;
			this.hbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox9]));
			w20.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.hbox7.Add(this.label12);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label12]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.IEntryFour = new global::Gtk.Entry();
			this.IEntryFour.WidthRequest = 70;
			this.IEntryFour.HeightRequest = 30;
			this.IEntryFour.CanFocus = true;
			this.IEntryFour.Name = "IEntryFour";
			this.IEntryFour.IsEditable = true;
			this.IEntryFour.MaxLength = 5;
			this.IEntryFour.InvisibleChar = '•';
			this.hbox7.Add(this.IEntryFour);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.IEntryFour]));
			w22.Position = 3;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.hbox7.Add(this.label13);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label13]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.IEntryFive = new global::Gtk.Entry();
			this.IEntryFive.WidthRequest = 10;
			this.IEntryFive.HeightRequest = 30;
			this.IEntryFive.CanFocus = true;
			this.IEntryFive.Name = "IEntryFive";
			this.IEntryFive.IsEditable = true;
			this.IEntryFive.MaxLength = 1;
			this.IEntryFive.InvisibleChar = '•';
			this.hbox7.Add(this.IEntryFive);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.IEntryFive]));
			w24.Position = 5;
			this.vbox3.Add(this.hbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 11;
			this.hbox8.BorderWidth = ((uint)(6));
			// Container child hbox8.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Price      :");
			this.hbox8.Add(this.label9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label9]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.PriceEntry = new global::Gtk.Entry();
			this.PriceEntry.HeightRequest = 30;
			this.PriceEntry.CanFocus = true;
			this.PriceEntry.Name = "PriceEntry";
			this.PriceEntry.IsEditable = true;
			this.PriceEntry.InvisibleChar = '•';
			this.hbox8.Add(this.PriceEntry);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.PriceEntry]));
			w27.Position = 1;
			this.vbox3.Add(this.hbox8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
			w28.Position = 5;
			w28.Expand = false;
			w28.Fill = false;
			w1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(w1[this.vbox3]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Internal child BookManagement.Gtksharp.BookInfoDialog.ActionArea
			global::Gtk.HButtonBox w30 = this.ActionArea;
			w30.Name = "dialog1_ActionArea";
			w30.Spacing = 10;
			w30.BorderWidth = ((uint)(5));
			w30.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelBtn = new global::Gtk.Button();
			this.CancelBtn.CanDefault = true;
			this.CancelBtn.CanFocus = true;
			this.CancelBtn.Name = "CancelBtn";
			this.CancelBtn.UseStock = true;
			this.CancelBtn.UseUnderline = true;
			this.CancelBtn.Label = "gtk-cancel";
			this.AddActionWidget(this.CancelBtn, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w30[this.CancelBtn]));
			w31.Expand = false;
			w31.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OkBtn = new global::Gtk.Button();
			this.OkBtn.CanDefault = true;
			this.OkBtn.CanFocus = true;
			this.OkBtn.Name = "OkBtn";
			this.OkBtn.UseStock = true;
			this.OkBtn.UseUnderline = true;
			this.OkBtn.Label = "gtk-ok";
			this.AddActionWidget(this.OkBtn, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w30[this.OkBtn]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.CancelBtn.Clicked += new global::System.EventHandler(this.On_CanceledBtn_Clicked);
			this.OkBtn.Clicked += new global::System.EventHandler(this.On_OkBtn_Clicked);
		}
	}
}
