
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView BooksView;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button InitdataBtn;

	private global::Gtk.Button AddBtn;

	private global::Gtk.Button DeleteBtn;

	private global::Gtk.Button SearchBtn;

	private global::Gtk.Button ModifyBtn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("BookManagement System");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.BooksView = new global::Gtk.TreeView();
		this.BooksView.CanFocus = true;
		this.BooksView.Name = "BooksView";
		this.BooksView.RulesHint = true;
		this.GtkScrolledWindow.Add(this.BooksView);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.InitdataBtn = new global::Gtk.Button();
		this.InitdataBtn.WidthRequest = 100;
		this.InitdataBtn.CanFocus = true;
		this.InitdataBtn.Name = "InitdataBtn";
		this.InitdataBtn.UseUnderline = true;
		this.InitdataBtn.Label = global::Mono.Unix.Catalog.GetString("Initdata");
		this.hbox1.Add(this.InitdataBtn);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.InitdataBtn]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.AddBtn = new global::Gtk.Button();
		this.AddBtn.WidthRequest = 100;
		this.AddBtn.CanFocus = true;
		this.AddBtn.Name = "AddBtn";
		this.AddBtn.UseUnderline = true;
		this.AddBtn.Label = global::Mono.Unix.Catalog.GetString("Add");
		this.hbox1.Add(this.AddBtn);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.AddBtn]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.DeleteBtn = new global::Gtk.Button();
		this.DeleteBtn.WidthRequest = 100;
		this.DeleteBtn.CanFocus = true;
		this.DeleteBtn.Name = "DeleteBtn";
		this.DeleteBtn.UseUnderline = true;
		this.DeleteBtn.Label = global::Mono.Unix.Catalog.GetString("Delete");
		this.hbox1.Add(this.DeleteBtn);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DeleteBtn]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.SearchBtn = new global::Gtk.Button();
		this.SearchBtn.WidthRequest = 100;
		this.SearchBtn.CanFocus = true;
		this.SearchBtn.Name = "SearchBtn";
		this.SearchBtn.UseUnderline = true;
		this.SearchBtn.Label = global::Mono.Unix.Catalog.GetString("Search");
		this.hbox1.Add(this.SearchBtn);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.SearchBtn]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ModifyBtn = new global::Gtk.Button();
		this.ModifyBtn.WidthRequest = 100;
		this.ModifyBtn.CanFocus = true;
		this.ModifyBtn.Name = "ModifyBtn";
		this.ModifyBtn.UseUnderline = true;
		this.ModifyBtn.Label = global::Mono.Unix.Catalog.GetString("Modify");
		this.hbox1.Add(this.ModifyBtn);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ModifyBtn]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 436;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.InitdataBtn.Clicked += new global::System.EventHandler(this.On_InitdataBtn_Clicked);
		this.AddBtn.Clicked += new global::System.EventHandler(this.On_AddBtn_Clicked);
		this.DeleteBtn.Clicked += new global::System.EventHandler(this.On_DeleteBtn_Clicked);
		this.SearchBtn.Clicked += new global::System.EventHandler(this.On_SearchBtn_Clicked);
		this.ModifyBtn.Clicked += new global::System.EventHandler(this.On_ModifyBtn_Clicked);
	}
}
