
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame MainFrame;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label Label_OperandX;

	private global::Gtk.Entry Entry_OperandX;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label Label_Operator;

	private global::Gtk.ComboBox ComboBox_Operators;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label Label_OperandY;

	private global::Gtk.Entry Entry_OperandY;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label Label_Result;

	private global::Gtk.HBox hbox5;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Button Btn_Calculate;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button Btn_ViewLog;

	private global::Gtk.Button Btn_WriteLog;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView TextV_Log;

	private global::Gtk.Button Btn_Exit;

	private global::Gtk.Label GtkLabel4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculator");
		this.TypeHint = ((global::Gdk.WindowTypeHint)(5));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(6));
		this.Resizable = false;
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainFrame = new global::Gtk.Frame();
		this.MainFrame.Name = "MainFrame";
		this.MainFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		this.MainFrame.BorderWidth = ((uint)(3));
		// Container child MainFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 10;
		this.vbox2.BorderWidth = ((uint)(15));
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Label_OperandX = new global::Gtk.Label();
		this.Label_OperandX.Name = "Label_OperandX";
		this.Label_OperandX.LabelProp = global::Mono.Unix.Catalog.GetString("OperandX :");
		this.hbox1.Add(this.Label_OperandX);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Label_OperandX]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Entry_OperandX = new global::Gtk.Entry();
		this.Entry_OperandX.CanFocus = true;
		this.Entry_OperandX.Name = "Entry_OperandX";
		this.Entry_OperandX.IsEditable = true;
		this.Entry_OperandX.InvisibleChar = '•';
		this.hbox1.Add(this.Entry_OperandX);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Entry_OperandX]));
		w2.Position = 1;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Label_Operator = new global::Gtk.Label();
		this.Label_Operator.Name = "Label_Operator";
		this.Label_Operator.LabelProp = global::Mono.Unix.Catalog.GetString("Operator   :");
		this.hbox3.Add(this.Label_Operator);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Label_Operator]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.ComboBox_Operators = global::Gtk.ComboBox.NewText();
		this.ComboBox_Operators.AppendText(global::Mono.Unix.Catalog.GetString("+"));
		this.ComboBox_Operators.AppendText(global::Mono.Unix.Catalog.GetString("-"));
		this.ComboBox_Operators.AppendText(global::Mono.Unix.Catalog.GetString("*"));
		this.ComboBox_Operators.AppendText(global::Mono.Unix.Catalog.GetString("/"));
		this.ComboBox_Operators.Name = "ComboBox_Operators";
		this.hbox3.Add(this.ComboBox_Operators);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.ComboBox_Operators]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Label_OperandY = new global::Gtk.Label();
		this.Label_OperandY.Name = "Label_OperandY";
		this.Label_OperandY.LabelProp = global::Mono.Unix.Catalog.GetString("OperandY :");
		this.hbox2.Add(this.Label_OperandY);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Label_OperandY]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Entry_OperandY = new global::Gtk.Entry();
		this.Entry_OperandY.CanFocus = true;
		this.Entry_OperandY.Name = "Entry_OperandY";
		this.Entry_OperandY.IsEditable = true;
		this.Entry_OperandY.InvisibleChar = '•';
		this.hbox2.Add(this.Entry_OperandY);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Entry_OperandY]));
		w8.Position = 1;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.HeightRequest = 30;
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Label_Result = new global::Gtk.Label();
		this.Label_Result.Name = "Label_Result";
		this.Label_Result.LabelProp = global::Mono.Unix.Catalog.GetString("Result          :");
		this.hbox4.Add(this.Label_Result);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Label_Result]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.hbox5.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hseparator1]));
		w12.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Btn_Calculate = new global::Gtk.Button();
		this.Btn_Calculate.CanFocus = true;
		this.Btn_Calculate.Name = "Btn_Calculate";
		this.Btn_Calculate.UseUnderline = true;
		this.Btn_Calculate.Label = global::Mono.Unix.Catalog.GetString("Calculate");
		this.hbox5.Add(this.Btn_Calculate);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Btn_Calculate]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.HeightRequest = 40;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Btn_ViewLog = new global::Gtk.Button();
		this.Btn_ViewLog.CanFocus = true;
		this.Btn_ViewLog.Name = "Btn_ViewLog";
		this.Btn_ViewLog.UseUnderline = true;
		this.Btn_ViewLog.Label = global::Mono.Unix.Catalog.GetString("ViewLog");
		this.fixed1.Add(this.Btn_ViewLog);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Btn_ViewLog]));
		w15.X = -3;
		w15.Y = 6;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Btn_WriteLog = new global::Gtk.Button();
		this.Btn_WriteLog.CanFocus = true;
		this.Btn_WriteLog.Name = "Btn_WriteLog";
		this.Btn_WriteLog.UseUnderline = true;
		this.Btn_WriteLog.Label = global::Mono.Unix.Catalog.GetString("WriteLog");
		this.fixed1.Add(this.Btn_WriteLog);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Btn_WriteLog]));
		w16.X = 363;
		w16.Y = 4;
		this.vbox2.Add(this.fixed1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed1]));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TextV_Log = new global::Gtk.TextView();
		this.TextV_Log.CanFocus = true;
		this.TextV_Log.Name = "TextV_Log";
		this.TextV_Log.Editable = false;
		this.GtkScrolledWindow.Add(this.TextV_Log);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w19.Position = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.Btn_Exit = new global::Gtk.Button();
		this.Btn_Exit.CanFocus = true;
		this.Btn_Exit.Name = "Btn_Exit";
		this.Btn_Exit.UseUnderline = true;
		this.Btn_Exit.Label = global::Mono.Unix.Catalog.GetString("Exit");
		this.vbox2.Add(this.Btn_Exit);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.Btn_Exit]));
		w20.Position = 7;
		w20.Expand = false;
		w20.Fill = false;
		this.GtkAlignment.Add(this.vbox2);
		this.MainFrame.Add(this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Calculator</b>");
		this.GtkLabel4.UseMarkup = true;
		this.MainFrame.LabelWidget = this.GtkLabel4;
		this.Add(this.MainFrame);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 502;
		this.DefaultHeight = 453;
		this.Show();
		this.Btn_Calculate.Clicked += new global::System.EventHandler(this.When_CalculateBtn_Clicked);
		this.Btn_ViewLog.Clicked += new global::System.EventHandler(this.When_ViewLogBtn_Clicked);
		this.Btn_WriteLog.Clicked += new global::System.EventHandler(this.When_WriteLogBtn_Clicked);
		this.Btn_Exit.Clicked += new global::System.EventHandler(this.When_ExitBtn_Clicked);
	}
}
